name: pr-check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  codeql-only:
    uses: guilhermelinosp/ci-templates/.github/workflows/codeql.yml@42c62912dd074fb8ad86c8703cb2d8300b424d61
