name: pr-check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  codeql-only:
    uses: guilhermelinosp/ci-templates/.github/workflows/codeql-analysis.yml@48298ecfe12661d07f7d4bf83448518c1870f4f7
