name: pr-check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  call-empty:
    uses: guilhermelinosp/ci-templates/.github/workflows/c-probe-empty.yml@3477522959a5c9875e1fb912e7a1015039d46e78

  call-perms:
    uses: guilhermelinosp/ci-templates/.github/workflows/c-probe-perms.yml@3477522959a5c9875e1fb912e7a1015039d46e78
